[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.25.0"
itertools = "0.12.0"
nom = "7.1.3"
nom_locate = "4.2.0"
pathfinding = "4.8.0"
